// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: magnetar.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFromNodePoolReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
}

func (x *GetFromNodePoolReq) Reset() {
	*x = GetFromNodePoolReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFromNodePoolReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFromNodePoolReq) ProtoMessage() {}

func (x *GetFromNodePoolReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFromNodePoolReq.ProtoReflect.Descriptor instead.
func (*GetFromNodePoolReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{0}
}

func (x *GetFromNodePoolReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetFromNodePoolResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *NodeStringified `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *GetFromNodePoolResp) Reset() {
	*x = GetFromNodePoolResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFromNodePoolResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFromNodePoolResp) ProtoMessage() {}

func (x *GetFromNodePoolResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFromNodePoolResp.ProtoReflect.Descriptor instead.
func (*GetFromNodePoolResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{1}
}

func (x *GetFromNodePoolResp) GetNode() *NodeStringified {
	if x != nil {
		return x.Node
	}
	return nil
}

type GetFromOrgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Org    string `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
}

func (x *GetFromOrgReq) Reset() {
	*x = GetFromOrgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFromOrgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFromOrgReq) ProtoMessage() {}

func (x *GetFromOrgReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFromOrgReq.ProtoReflect.Descriptor instead.
func (*GetFromOrgReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{2}
}

func (x *GetFromOrgReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetFromOrgReq) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type GetFromOrgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *NodeStringified `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *GetFromOrgResp) Reset() {
	*x = GetFromOrgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFromOrgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFromOrgResp) ProtoMessage() {}

func (x *GetFromOrgResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFromOrgResp.ProtoReflect.Descriptor instead.
func (*GetFromOrgResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{3}
}

func (x *GetFromOrgResp) GetNode() *NodeStringified {
	if x != nil {
		return x.Node
	}
	return nil
}

type ClaimOwnershipReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query []*Selector `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty"`
	Org   string      `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
}

func (x *ClaimOwnershipReq) Reset() {
	*x = ClaimOwnershipReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimOwnershipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimOwnershipReq) ProtoMessage() {}

func (x *ClaimOwnershipReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimOwnershipReq.ProtoReflect.Descriptor instead.
func (*ClaimOwnershipReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimOwnershipReq) GetQuery() []*Selector {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ClaimOwnershipReq) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type ClaimOwnershipResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node []*NodeStringified `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
}

func (x *ClaimOwnershipResp) Reset() {
	*x = ClaimOwnershipResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimOwnershipResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimOwnershipResp) ProtoMessage() {}

func (x *ClaimOwnershipResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimOwnershipResp.ProtoReflect.Descriptor instead.
func (*ClaimOwnershipResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimOwnershipResp) GetNode() []*NodeStringified {
	if x != nil {
		return x.Node
	}
	return nil
}

type ListAllNodesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAllNodesReq) Reset() {
	*x = ListAllNodesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllNodesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllNodesReq) ProtoMessage() {}

func (x *ListAllNodesReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllNodesReq.ProtoReflect.Descriptor instead.
func (*ListAllNodesReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{6}
}

type ListAllNodesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NodeStringified `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *ListAllNodesResp) Reset() {
	*x = ListAllNodesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllNodesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllNodesResp) ProtoMessage() {}

func (x *ListAllNodesResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllNodesResp.ProtoReflect.Descriptor instead.
func (*ListAllNodesResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{7}
}

func (x *ListAllNodesResp) GetNodes() []*NodeStringified {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ListNodePoolReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListNodePoolReq) Reset() {
	*x = ListNodePoolReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNodePoolReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodePoolReq) ProtoMessage() {}

func (x *ListNodePoolReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodePoolReq.ProtoReflect.Descriptor instead.
func (*ListNodePoolReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{8}
}

type ListNodePoolResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NodeStringified `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *ListNodePoolResp) Reset() {
	*x = ListNodePoolResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNodePoolResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodePoolResp) ProtoMessage() {}

func (x *ListNodePoolResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodePoolResp.ProtoReflect.Descriptor instead.
func (*ListNodePoolResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{9}
}

func (x *ListNodePoolResp) GetNodes() []*NodeStringified {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ListOrgOwnedNodesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Org string `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
}

func (x *ListOrgOwnedNodesReq) Reset() {
	*x = ListOrgOwnedNodesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOrgOwnedNodesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrgOwnedNodesReq) ProtoMessage() {}

func (x *ListOrgOwnedNodesReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrgOwnedNodesReq.ProtoReflect.Descriptor instead.
func (*ListOrgOwnedNodesReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{10}
}

func (x *ListOrgOwnedNodesReq) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type ListOrgOwnedNodesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NodeStringified `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *ListOrgOwnedNodesResp) Reset() {
	*x = ListOrgOwnedNodesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOrgOwnedNodesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrgOwnedNodesResp) ProtoMessage() {}

func (x *ListOrgOwnedNodesResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrgOwnedNodesResp.ProtoReflect.Descriptor instead.
func (*ListOrgOwnedNodesResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{11}
}

func (x *ListOrgOwnedNodesResp) GetNodes() []*NodeStringified {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Selector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LabelKey string `protobuf:"bytes,3,opt,name=labelKey,proto3" json:"labelKey,omitempty"`
	ShouldBe string `protobuf:"bytes,2,opt,name=shouldBe,proto3" json:"shouldBe,omitempty"`
	Value    string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Selector) Reset() {
	*x = Selector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selector) ProtoMessage() {}

func (x *Selector) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selector.ProtoReflect.Descriptor instead.
func (*Selector) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{12}
}

func (x *Selector) GetLabelKey() string {
	if x != nil {
		return x.LabelKey
	}
	return ""
}

func (x *Selector) GetShouldBe() string {
	if x != nil {
		return x.ShouldBe
	}
	return ""
}

func (x *Selector) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type QueryNodePoolReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query []*Selector `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty"`
}

func (x *QueryNodePoolReq) Reset() {
	*x = QueryNodePoolReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryNodePoolReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNodePoolReq) ProtoMessage() {}

func (x *QueryNodePoolReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNodePoolReq.ProtoReflect.Descriptor instead.
func (*QueryNodePoolReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{13}
}

func (x *QueryNodePoolReq) GetQuery() []*Selector {
	if x != nil {
		return x.Query
	}
	return nil
}

type QueryNodePoolResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NodeStringified `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *QueryNodePoolResp) Reset() {
	*x = QueryNodePoolResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryNodePoolResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNodePoolResp) ProtoMessage() {}

func (x *QueryNodePoolResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNodePoolResp.ProtoReflect.Descriptor instead.
func (*QueryNodePoolResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{14}
}

func (x *QueryNodePoolResp) GetNodes() []*NodeStringified {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type QueryOrgOwnedNodesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query []*Selector `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty"`
	Org   string      `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
}

func (x *QueryOrgOwnedNodesReq) Reset() {
	*x = QueryOrgOwnedNodesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrgOwnedNodesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrgOwnedNodesReq) ProtoMessage() {}

func (x *QueryOrgOwnedNodesReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrgOwnedNodesReq.ProtoReflect.Descriptor instead.
func (*QueryOrgOwnedNodesReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{15}
}

func (x *QueryOrgOwnedNodesReq) GetQuery() []*Selector {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *QueryOrgOwnedNodesReq) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type QueryOrgOwnedNodesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NodeStringified `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *QueryOrgOwnedNodesResp) Reset() {
	*x = QueryOrgOwnedNodesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrgOwnedNodesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrgOwnedNodesResp) ProtoMessage() {}

func (x *QueryOrgOwnedNodesResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrgOwnedNodesResp.ProtoReflect.Descriptor instead.
func (*QueryOrgOwnedNodesResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{16}
}

func (x *QueryOrgOwnedNodesResp) GetNodes() []*NodeStringified {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type PutBoolLabelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string     `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Label  *BoolLabel `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Org    string     `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
}

func (x *PutBoolLabelReq) Reset() {
	*x = PutBoolLabelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutBoolLabelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBoolLabelReq) ProtoMessage() {}

func (x *PutBoolLabelReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBoolLabelReq.ProtoReflect.Descriptor instead.
func (*PutBoolLabelReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{17}
}

func (x *PutBoolLabelReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PutBoolLabelReq) GetLabel() *BoolLabel {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *PutBoolLabelReq) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type PutFloat64LabelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string        `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Label  *Float64Label `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Org    string        `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
}

func (x *PutFloat64LabelReq) Reset() {
	*x = PutFloat64LabelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutFloat64LabelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFloat64LabelReq) ProtoMessage() {}

func (x *PutFloat64LabelReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFloat64LabelReq.ProtoReflect.Descriptor instead.
func (*PutFloat64LabelReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{18}
}

func (x *PutFloat64LabelReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PutFloat64LabelReq) GetLabel() *Float64Label {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *PutFloat64LabelReq) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type PutStringLabelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string       `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Label  *StringLabel `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Org    string       `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
}

func (x *PutStringLabelReq) Reset() {
	*x = PutStringLabelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutStringLabelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutStringLabelReq) ProtoMessage() {}

func (x *PutStringLabelReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutStringLabelReq.ProtoReflect.Descriptor instead.
func (*PutStringLabelReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{19}
}

func (x *PutStringLabelReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PutStringLabelReq) GetLabel() *StringLabel {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *PutStringLabelReq) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type PutLabelResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *NodeStringified `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *PutLabelResp) Reset() {
	*x = PutLabelResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutLabelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutLabelResp) ProtoMessage() {}

func (x *PutLabelResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutLabelResp.ProtoReflect.Descriptor instead.
func (*PutLabelResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{20}
}

func (x *PutLabelResp) GetNode() *NodeStringified {
	if x != nil {
		return x.Node
	}
	return nil
}

type DeleteLabelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId   string `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	LabelKey string `protobuf:"bytes,2,opt,name=labelKey,proto3" json:"labelKey,omitempty"`
	Org      string `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
}

func (x *DeleteLabelReq) Reset() {
	*x = DeleteLabelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLabelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLabelReq) ProtoMessage() {}

func (x *DeleteLabelReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLabelReq.ProtoReflect.Descriptor instead.
func (*DeleteLabelReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteLabelReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeleteLabelReq) GetLabelKey() string {
	if x != nil {
		return x.LabelKey
	}
	return ""
}

func (x *DeleteLabelReq) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type DeleteLabelResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *NodeStringified `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *DeleteLabelResp) Reset() {
	*x = DeleteLabelResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLabelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLabelResp) ProtoMessage() {}

func (x *DeleteLabelResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLabelResp.ProtoReflect.Descriptor instead.
func (*DeleteLabelResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteLabelResp) GetNode() *NodeStringified {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_magnetar_proto protoreflect.FileDescriptor

var file_magnetar_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x61,
	0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x6f, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2a, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x39,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x72, 0x67, 0x22, 0x3c, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x4c, 0x0a, 0x11, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6f, 0x72, 0x67, 0x22, 0x40, 0x0a, 0x12, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x6c, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x40, 0x0a, 0x10, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6c, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c,
	0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x11, 0x0a, 0x0f,
	0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x22,
	0x40, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x22, 0x28, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x67, 0x4f, 0x77, 0x6e, 0x65,
	0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x72, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x72, 0x67, 0x22, 0x45, 0x0a, 0x15, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x72, 0x67, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x05, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x22, 0x58, 0x0a, 0x08, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68,
	0x6f, 0x75, 0x6c, 0x64, 0x42, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68,
	0x6f, 0x75, 0x6c, 0x64, 0x42, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x39, 0x0a, 0x10,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x25, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x41, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x50, 0x0a, 0x15, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4f, 0x72, 0x67, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x72,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x72, 0x67, 0x22, 0x46, 0x0a, 0x16,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x67, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x05, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x22, 0x63, 0x0a, 0x0f, 0x50, 0x75, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12,
	0x26, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x72, 0x67, 0x22, 0x69, 0x0a, 0x12, 0x50, 0x75, 0x74,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6f, 0x72, 0x67, 0x22, 0x67, 0x0a, 0x11, 0x50, 0x75, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x28, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6f,
	0x72, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x72, 0x67, 0x22, 0x3a, 0x0a,
	0x0c, 0x50, 0x75, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x56, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x4b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x4b, 0x65, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x72,
	0x67, 0x22, 0x3d, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x32, 0xd6, 0x06, 0x0a, 0x08, 0x4d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x61, 0x72, 0x12, 0x4a, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x6f, 0x6c,
	0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d,
	0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x50,
	0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x72, 0x67, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x72, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x41, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x12,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65,
	0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x50, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x67, 0x4f, 0x77, 0x6e,
	0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x67, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x72, 0x67, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x6f, 0x64,
	0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x6f, 0x64, 0x65,
	0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x12, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4f, 0x72, 0x67, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73,
	0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72,
	0x67, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x67, 0x4f,
	0x77, 0x6e, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x0c, 0x50, 0x75, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x75, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x43,
	0x0a, 0x0f, 0x50, 0x75, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x36, 0x34, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0e, 0x50, 0x75, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75,
	0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c,
	0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x31, 0x32, 0x73, 0x2f, 0x6d, 0x61, 0x67,
	0x6e, 0x65, 0x74, 0x61, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_magnetar_proto_rawDescOnce sync.Once
	file_magnetar_proto_rawDescData = file_magnetar_proto_rawDesc
)

func file_magnetar_proto_rawDescGZIP() []byte {
	file_magnetar_proto_rawDescOnce.Do(func() {
		file_magnetar_proto_rawDescData = protoimpl.X.CompressGZIP(file_magnetar_proto_rawDescData)
	})
	return file_magnetar_proto_rawDescData
}

var file_magnetar_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_magnetar_proto_goTypes = []interface{}{
	(*GetFromNodePoolReq)(nil),     // 0: proto.GetFromNodePoolReq
	(*GetFromNodePoolResp)(nil),    // 1: proto.GetFromNodePoolResp
	(*GetFromOrgReq)(nil),          // 2: proto.GetFromOrgReq
	(*GetFromOrgResp)(nil),         // 3: proto.GetFromOrgResp
	(*ClaimOwnershipReq)(nil),      // 4: proto.ClaimOwnershipReq
	(*ClaimOwnershipResp)(nil),     // 5: proto.ClaimOwnershipResp
	(*ListAllNodesReq)(nil),        // 6: proto.ListAllNodesReq
	(*ListAllNodesResp)(nil),       // 7: proto.ListAllNodesResp
	(*ListNodePoolReq)(nil),        // 8: proto.ListNodePoolReq
	(*ListNodePoolResp)(nil),       // 9: proto.ListNodePoolResp
	(*ListOrgOwnedNodesReq)(nil),   // 10: proto.ListOrgOwnedNodesReq
	(*ListOrgOwnedNodesResp)(nil),  // 11: proto.ListOrgOwnedNodesResp
	(*Selector)(nil),               // 12: proto.Selector
	(*QueryNodePoolReq)(nil),       // 13: proto.QueryNodePoolReq
	(*QueryNodePoolResp)(nil),      // 14: proto.QueryNodePoolResp
	(*QueryOrgOwnedNodesReq)(nil),  // 15: proto.QueryOrgOwnedNodesReq
	(*QueryOrgOwnedNodesResp)(nil), // 16: proto.QueryOrgOwnedNodesResp
	(*PutBoolLabelReq)(nil),        // 17: proto.PutBoolLabelReq
	(*PutFloat64LabelReq)(nil),     // 18: proto.PutFloat64LabelReq
	(*PutStringLabelReq)(nil),      // 19: proto.PutStringLabelReq
	(*PutLabelResp)(nil),           // 20: proto.PutLabelResp
	(*DeleteLabelReq)(nil),         // 21: proto.DeleteLabelReq
	(*DeleteLabelResp)(nil),        // 22: proto.DeleteLabelResp
	(*NodeStringified)(nil),        // 23: proto.NodeStringified
	(*BoolLabel)(nil),              // 24: proto.BoolLabel
	(*Float64Label)(nil),           // 25: proto.Float64Label
	(*StringLabel)(nil),            // 26: proto.StringLabel
}
var file_magnetar_proto_depIdxs = []int32{
	23, // 0: proto.GetFromNodePoolResp.node:type_name -> proto.NodeStringified
	23, // 1: proto.GetFromOrgResp.node:type_name -> proto.NodeStringified
	12, // 2: proto.ClaimOwnershipReq.query:type_name -> proto.Selector
	23, // 3: proto.ClaimOwnershipResp.node:type_name -> proto.NodeStringified
	23, // 4: proto.ListAllNodesResp.nodes:type_name -> proto.NodeStringified
	23, // 5: proto.ListNodePoolResp.nodes:type_name -> proto.NodeStringified
	23, // 6: proto.ListOrgOwnedNodesResp.nodes:type_name -> proto.NodeStringified
	12, // 7: proto.QueryNodePoolReq.query:type_name -> proto.Selector
	23, // 8: proto.QueryNodePoolResp.nodes:type_name -> proto.NodeStringified
	12, // 9: proto.QueryOrgOwnedNodesReq.query:type_name -> proto.Selector
	23, // 10: proto.QueryOrgOwnedNodesResp.nodes:type_name -> proto.NodeStringified
	24, // 11: proto.PutBoolLabelReq.label:type_name -> proto.BoolLabel
	25, // 12: proto.PutFloat64LabelReq.label:type_name -> proto.Float64Label
	26, // 13: proto.PutStringLabelReq.label:type_name -> proto.StringLabel
	23, // 14: proto.PutLabelResp.node:type_name -> proto.NodeStringified
	23, // 15: proto.DeleteLabelResp.node:type_name -> proto.NodeStringified
	0,  // 16: proto.Magnetar.GetFromNodePool:input_type -> proto.GetFromNodePoolReq
	2,  // 17: proto.Magnetar.GetFromOrg:input_type -> proto.GetFromOrgReq
	4,  // 18: proto.Magnetar.ClaimOwnership:input_type -> proto.ClaimOwnershipReq
	8,  // 19: proto.Magnetar.ListNodePool:input_type -> proto.ListNodePoolReq
	10, // 20: proto.Magnetar.ListOrgOwnedNodes:input_type -> proto.ListOrgOwnedNodesReq
	13, // 21: proto.Magnetar.QueryNodePool:input_type -> proto.QueryNodePoolReq
	15, // 22: proto.Magnetar.QueryOrgOwnedNodes:input_type -> proto.QueryOrgOwnedNodesReq
	17, // 23: proto.Magnetar.PutBoolLabel:input_type -> proto.PutBoolLabelReq
	18, // 24: proto.Magnetar.PutFloat64Label:input_type -> proto.PutFloat64LabelReq
	19, // 25: proto.Magnetar.PutStringLabel:input_type -> proto.PutStringLabelReq
	21, // 26: proto.Magnetar.DeleteLabel:input_type -> proto.DeleteLabelReq
	6,  // 27: proto.Magnetar.ListAllNodes:input_type -> proto.ListAllNodesReq
	1,  // 28: proto.Magnetar.GetFromNodePool:output_type -> proto.GetFromNodePoolResp
	3,  // 29: proto.Magnetar.GetFromOrg:output_type -> proto.GetFromOrgResp
	5,  // 30: proto.Magnetar.ClaimOwnership:output_type -> proto.ClaimOwnershipResp
	9,  // 31: proto.Magnetar.ListNodePool:output_type -> proto.ListNodePoolResp
	11, // 32: proto.Magnetar.ListOrgOwnedNodes:output_type -> proto.ListOrgOwnedNodesResp
	14, // 33: proto.Magnetar.QueryNodePool:output_type -> proto.QueryNodePoolResp
	16, // 34: proto.Magnetar.QueryOrgOwnedNodes:output_type -> proto.QueryOrgOwnedNodesResp
	20, // 35: proto.Magnetar.PutBoolLabel:output_type -> proto.PutLabelResp
	20, // 36: proto.Magnetar.PutFloat64Label:output_type -> proto.PutLabelResp
	20, // 37: proto.Magnetar.PutStringLabel:output_type -> proto.PutLabelResp
	22, // 38: proto.Magnetar.DeleteLabel:output_type -> proto.DeleteLabelResp
	7,  // 39: proto.Magnetar.ListAllNodes:output_type -> proto.ListAllNodesResp
	28, // [28:40] is the sub-list for method output_type
	16, // [16:28] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_magnetar_proto_init() }
func file_magnetar_proto_init() {
	if File_magnetar_proto != nil {
		return
	}
	file_magnetar_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_magnetar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFromNodePoolReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFromNodePoolResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFromOrgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFromOrgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimOwnershipReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimOwnershipResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllNodesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllNodesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNodePoolReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNodePoolResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOrgOwnedNodesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOrgOwnedNodesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Selector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryNodePoolReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryNodePoolResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrgOwnedNodesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrgOwnedNodesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutBoolLabelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutFloat64LabelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutStringLabelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutLabelResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLabelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLabelResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_magnetar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_magnetar_proto_goTypes,
		DependencyIndexes: file_magnetar_proto_depIdxs,
		MessageInfos:      file_magnetar_proto_msgTypes,
	}.Build()
	File_magnetar_proto = out.File
	file_magnetar_proto_rawDesc = nil
	file_magnetar_proto_goTypes = nil
	file_magnetar_proto_depIdxs = nil
}
