name: Go CI

on:
  push:
    branches:
      - main

jobs:
  go-ci:
      runs-on: ubuntu-latest

      steps:
        - name: Check out code
          uses: actions/checkout@v3

        - name: Move to parent directory
          run: cd ..

        - name: Clone gravity repository
          run: git clone https://github.com/test-diplomski/gravity.git

        - name: Move back to repository directory
          run: cd -

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.22.3'

        - name: Install dependencies
          run: go mod download

        - name: Build
          run: go build -v ./...
  # docker:
  #   runs-on: ubuntu-latest
  #   needs: go-ci

  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: .
  #         file: Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/magnetar:latest
